/**
 * Turns the precomputed `odometerCatalog.json` into odometer PID candidates
 * for a given vehicle: resolve which manufacturer applies (by the VIN's WMI,
 * falling back to fuzzy-matching the car's `make` text), then pull out its
 * pre-filtered odometer/mileage DIDs. The standard OBD-II PID is always
 * appended last as a fallback.
 *
 * `odometerCatalog.json` is generated by `scripts/generate-odometer-catalog.mjs`
 * from the full vendored Delphi-OBD manufacturer catalogs - each of those is
 * ~1-2MB with ~2000 DIDs (plus ecus/routines/coding_blocks/adaptations/
 * actuator_tests/live_pids/dtc_extended_data, none of which any code path
 * reads), of which only 1-2 DIDs per manufacturer are ever odometer-related.
 * Shipping all of that just for this lookup isn't worth it, so only the
 * already-filtered slice is bundled directly (no lazy asset load needed -
 * it's tiny). Re-run the generator script if the vendored catalog set is
 * refreshed from upstream.
 */

import odometerCatalog from '@/obd/catalogs/odometerCatalog.json';
import type { DidDecoder } from '@/obd/catalogs/types';
import manufacturerNames from '@/obd/catalogs/manufacturerNames.json';
import wmiIndex from '@/obd/catalogs/wmiIndex.json';
import { STANDARD_ODOMETER_PID, type OdometerPidDef } from '@/obd/pids';

interface OdometerDidEntry {
  name: string;
  did: string;
  ecu_address?: string;
  decoder?: DidDecoder;
  verified?: boolean;
}

const ODOMETER_CATALOG = odometerCatalog as Record<string, { display_name: string; dids: OdometerDidEntry[] }>;

function normalize(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]/g, '');
}

/** Resolves an odometer-catalog key for this vehicle: VIN's WMI first (exact), then a fuzzy match on `make`. */
function resolveCatalogKey(vin: string | null, make: string | null): string | null {
  const wmi = vin && vin.length >= 3 ? vin.slice(0, 3).toUpperCase() : null;
  const byWmi = wmi ? (wmiIndex as Record<string, string>)[wmi] : undefined;
  if (byWmi) return byWmi;

  if (!make) return null;
  const normalizedMake = normalize(make);
  if (!normalizedMake) return null;

  for (const [key, displayName] of Object.entries(manufacturerNames as Record<string, string>)) {
    const normalizedDisplay = normalize(displayName);
    if (normalizedDisplay.includes(normalizedMake) || normalizedMake.includes(normalizedDisplay)) {
      return key;
    }
  }
  return null;
}

/**
 * Decodes response bytes as an unsigned big/little-endian integer with the
 * DID's scale/offset applied. Deliberately permissive - the catalog's `hex`
 * decoder kind (no documented scale) still means "read these bytes as a
 * plain integer", it's just not been assigned a scale/offset yet.
 */
function decodeDidBytes(bytes: number[], decoder: DidDecoder | undefined): number | null {
  if (bytes.length === 0) return null;
  const littleEndian = decoder?.kind?.endsWith('_le') ?? false;
  const ordered = littleEndian ? [...bytes].reverse() : bytes;
  const raw = ordered.reduce((acc, byte) => acc * 256 + byte, 0);
  if (raw === 2 ** (ordered.length * 8) - 1) return null; // all-bits-set - adapter's "not supported" sentinel
  return raw * (decoder?.scale ?? 1) + (decoder?.offset ?? 0);
}

function toOdometerPidDef(did: OdometerDidEntry, sourceLabel: string): OdometerPidDef {
  return {
    label: `${sourceLabel}: ${did.name}`,
    mode: '22',
    pid: did.did,
    ecuHeader: did.ecu_address?.replace(/^0x/i, ''),
    decode: (bytes) => decodeDidBytes(bytes, did.decoder),
  };
}

export async function odometerCandidatesForVehicle(vin: string | null, make: string | null): Promise<OdometerPidDef[]> {
  const key = resolveCatalogKey(vin, make);
  const entry = key ? ODOMETER_CATALOG[key] : undefined;
  if (!entry) return [STANDARD_ODOMETER_PID];

  // Precomputed already filtered to odometer-like DIDs and sorted verified-first.
  const matches = entry.dids.map((did) => toOdometerPidDef(did, entry.display_name));
  return [...matches, STANDARD_ODOMETER_PID];
}
