export { lookupDtc } from '@/obd/catalogs/dtc';
export { odometerCandidatesForVehicle } from '@/obd/catalogs/odometerDids';
export { findUartProfile, openElmConnection, parseHexResponse, requestPid, requestVin } from '@/obd/elm327';
export type { UartProfile } from '@/obd/elm327';
export { STANDARD_ODOMETER_PID } from '@/obd/pids';
export type { OdometerPidDef } from '@/obd/pids';
export { scanVehicleInfo, syncOdometer } from '@/obd/scanVehicle';
export type { ScanStep, VehicleScanResult } from '@/obd/scanVehicle';
export { decodeVin, resetVinDecoder, setVinDecoder } from '@/obd/vin';
export type { DecodedVin, VinDecoder } from '@/obd/vin';
